#!/bin/bash

echo "🚀 AWS Amplify 배포 가이드"
echo "========================="
echo ""
echo "AWS Amplify는 Git 기반 자동 배포를 사용합니다."
echo "아래 단계를 따라 설정하세요:"
echo ""
echo "1. AWS Amplify Console 접속:"
echo "   https://console.aws.amazon.com/amplify/"
echo ""
echo "2. 'New app' > 'Host web app' 클릭"
echo ""
echo "3. Git provider 선택 (GitHub, GitLab, Bitbucket 등)"
echo ""
echo "4. Repository와 branch 선택"
echo ""
echo "5. App name 설정: 'amond-frontend' (예시)"
echo ""
echo "6. Build settings:"
echo "   - amplify.yml이 자동으로 감지됩니다"
echo "   - Framework: Next.js - SSR 선택"
echo ""
echo "7. Environment variables 설정 (Advanced settings):"
echo "   필요한 환경 변수들:"
echo "   - NEXT_PUBLIC_API_SERVER_URL"
echo "   - NEXT_PUBLIC_WEB_SERVER_URL"
echo "   - 기타 .env 파일의 변수들"
echo ""
echo "8. 'Save and deploy' 클릭"
echo ""
echo "📝 중요 사항:"
echo "- 첫 배포는 10-15분 정도 소요됩니다"
echo "- 이후 push 시 자동으로 배포됩니다"
echo "- Custom domain 설정 가능합니다"
echo "- CloudFront CDN이 자동으로 설정됩니다"
echo ""
echo "🔗 배포 후 URL:"
echo "https://[branch-name].[app-id].amplifyapp.com"
echo ""
echo "📚 추가 설정:"
echo "- Custom domain: App settings > Domain management"
echo "- 환경 변수: App settings > Environment variables"
echo "- Build settings: App settings > Build settings"
echo ""