import NotFound404Page from "@/component/pageComponent/404";
import Head from "next/head";

export default function NotFound404() {
  return (
    <>
      <Head>
        <title>Example App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NotFound404Page />
      </main>
    </>
  );
}
